// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwoteszpvvefbopbbvrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53b3Rlc3pwdnZlZmJvcGJidnJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NzY1MzQsImV4cCI6MjA2NTI1MjUzNH0.x9Ncuy3O_ZHEjcG-9x_Psa5eHweviIyKuh0OiFCbExI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);